### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by denbue** [MacPass/MacPassHTTP#16]
First: thanks for the check on my issue #14 . I followed your new walkthrough which only results in build fails on my computer:

Could you have a look at the terminal output? Thanks!

 (removed output)

**Comment by mstarke** [comment]
The compiler complains about not finding any of the MacPass headers, that leads me to think that either you're not using the same folder layout as stated in the readme or you did not correctly pull everything from the MacPass repository.

**Comment by denbue** [comment]
I've found the error: In the xcodeproject the folder layout was set different. In `Build Settings -> Search Paths -> Header Search Path` the option was set to `$(PROJECT_DIR)/../MacPass` . I changed it to `$(PROJECT_DIR)/MacPass` and the Build succeeded without any errors.
Everything is working fine now.

Please check Line 353 of `MacPassHTTP.xcodeproj/project.pbxproj`:

`HEADER_SEARCH_PATHS = "$(PROJECT_DIR)/../MacPass/**;`

**Comment by mstarke** [comment]
As I was saying, you're not using the same folder layout as described in the Readme. And thus need to change the settings. But that's also explained in the Readme. But I have to hand it so you, you've found another bug in the Readme. There's a missing `cd ..` to get the same folder layout. If followed by the book the result is your layout but then - as you've found out - the project settings are not correct.

This should now be fixed with 184774650f97449ae54851d659d55c8136543456
