### ISSUE TITLE
Does not work with MacPass v0.6.2

### ISSUE THREAD

**Issue by akcasoy** [MacPass/MacPassHTTP#26]
I have just installed the MacPass v0.6.2. As the instructions suggest, I have copied the MacPassHTTP.mpplugin file to ~/Library/Application Support/MacPass/, i do not see any plugin in the plugins section of the MacPass Preferences (even if the "load unsecure Plugins" is checked). 

PS: I did not have any "MacPass" folder under Application Support originally. I had to create one by myself. I do not know if this error may have sth to do with that.

PS2: my OS is macOS Sierra (may be this is the problem?)

**Comment by mstarke** [comment]
Can you take a look at the log?

**Comment by akcasoy** [comment]
how/where can i see the log?

**Comment by mstarke** [comment]
Open console.app and look at the system log

**Comment by akcasoy** [comment]
When i open the app, this is logged from the process "MacPass" :

> Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.

Other than this, there is not any log when i open the db, open the preferences, or open the tab "Plugins"

**Comment by mstarke** [comment]
I seem to recall that under 10.12 the logging is only enabled in debug mode due to some changes do NSLog. Normally MacPass tells you what plugins it has found and loaded or if any where rejected and the reason. I'll try to dig a bit further to offer more help.

**Comment by patrickwerz** [comment]
I have exactly the same problem like akcasoy.... Would be great if you could fix that. Thanks in advance...

**Comment by ParadiseDS** [comment]
I just built MacPass and MacPassHTTP from source of latest HEAD under macOS Sierra 10.12.2 and after check 'Load unsecure Plugins' the plugin just appeared in the list as expected. Maybe the building from source operation do some tricks so that it can load the plugin successfully.

When chromelPass tries connecting to MacPassHTTP, the authentication windows pops and, however, even the 'Allow access!'  button is clicked, the authentication window doesn't disappear and stays on the front so that no operation can be done with the MacPass/database.

With the authentication window stay on the front (after 'allow' button is clicked), chromelPass can work properly as if the authentication is successful. But after restarting MacPass (force quit and reopened) the authentication status is missing (of course as nothing is saved) so I have to reset chromelPass otherwise it tries to connect with the previous key and fails afterwards. This is quite bothering.

OS: macOS Sierra 10.12.2. MacPass and MacPassHTTP are both built from the latest HEAD.

**EDIT**: The system.log throws the following messages each time MacPass is launched and I didn't know if they are relevant

```
Dec 19 15:07:10 PDS-rmbp MacPass[98662]: assertion failed: 16C67: libxpc.dylib + 74307 [65E41BB6-EBD5-3D93-B0BE-B190CEE4DD93]: 0x89
Dec 19 15:07:17 PDS-rmbp MacPass[98662]: BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked
```

**Comment by mstarke** [comment]
@ParadiseDS the hanging Dialogs is a reported bug that I did not investigate any further. The Access without authentification is a serious bug. You log entry looks like a good start.

**Comment by analyticd** [comment]
Works fine for me with Passifox in Firefox 50.1, MacPass on HEAD, fef22bce05838c71c98354d2d9f229b4c1d7b0a7, MacPassHTTP on HEAD, 17f3534f1d163356444c0fa3c090e38964e98670, macOS Sierra. The key is to use HEAD and not the tagged alpha release referenced by the OP. Hope this helps someone.

**Comment by mstarke** [comment]
MacPassHTTP continuous works (again) with MacPass continuous
