### ISSUE TITLE
Load plugin dialog: wrong translation, load unsecure and unsigned plugin

### ISSUE THREAD

**Issue by ryanthara** [MacPass/MacPassHTTP#53]
Hello

I'm wondering about this dialog. It shows, that the plugin is not signed correctly. 

Additionally the option says that only correctly signed plugins will be loaded, but is this possible without a correctly signed plugin?

<img width="512" alt="load-unsecure-plugins_and_false-signed-plugins" src="https://user-images.githubusercontent.com/7117072/41820411-c7dc6338-77d1-11e8-92d5-d5d4d5a3d89b.png">

Where will I see, that the plugin works correctly?

**Comment by mstarke** [comment]
The description for the setting is wrong. It should state the exact opposite. This is already fixed in master. The plugin settings did expand in functionality. Until recently you would not see any plugins that where rejected. This has been changed to the current setup. If a plugin isn't loaded it will still be listed but a warning or a bomb is displayed as icon to show the error as well as an error message to see what went wrong. If you check the "load insecure plugins" box, the plugin will be loaded and not error should be displayed.

**Comment by ryanthara** [comment]
Ok, that's a good news. At the moment the plugin is still working without set checkbox. Is there something additional wrong?
